name: Deploy com Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Construir imagem Docker e rodar o contêiner
        run: |
          docker build -t app-deploy-demo .
          docker run -d -p 8080:8080 app-deploy-demo
